apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kshark.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kshark.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule.cron | quote }}
  suspend: {{ .Values.schedule.suspend }}
  successfulJobsHistoryLimit: {{ .Values.schedule.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.schedule.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "kshark.labels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "kshark.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: kshark
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                {{- toYaml .Values.probe.args | nindent 16 }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              volumeMounts:
                - name: reports
                  mountPath: /reports
                {{- if .Values.securityContext.readOnlyRootFilesystem }}
                - name: tmp
                  mountPath: /tmp
                {{- end }}
          volumes:
            - name: reports
              {{- if .Values.persistence.enabled }}
              persistentVolumeClaim:
                claimName: {{ include "kshark.fullname" . }}-reports
              {{- else }}
              emptyDir: {}
              {{- end }}
            {{- if .Values.securityContext.readOnlyRootFilesystem }}
            - name: tmp
              emptyDir: {}
            {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
